#ifndef TIPOERROR_H_INCLUDED
#define TIPOERROR_H_INCLUDED
#include "String.h"
typedef enum { SIN_ERROR, BRUJA_YA_EXISTE, BRUJA_NO_EXISTE,
BRUJA_NO_ES_SUPREMA, COMUN_NO_EN_DICCIO, DICCIO_VACIO, BRUJA_NO_MAS_HECHIZOS,
NO_EXISTE_HECHIZO, SUPREMA_NO_EXISTE, COMUN_YA_EXISTE, FECHA_INVALIDA
 } TipoError;

String getNombreError(TipoError t);

#endif // TIPOERROR_H_INCLUDED
